version: '3'

services:
  findafriend:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432
    env:
      POSTGRESQL_USERNAME: pets
      POSTGRESQL_PASSWORD: pets
      POSTGRESQL_DATABASE: findafriend
